#!/usr/bin/env python

import rospy
from egh450_image_processor.image_processor import ImageProcessor

if __name__ == '__main__':
	# Initialize
	rospy.init_node('egh450_image_processor', anonymous=True)

	ip = ImageProcessor()

	rospy.loginfo("Processing images...")

	# Loop here until quit
	try:
		rospy.spin()

	except rospy.ROSInterruptException:
		# Shutdown
		ip.shutdown()

